// USER CONSTANT
export const CREATE_USER="CREATE_USER";
export const GET_USER="GET_USER";
export const GET_USER_BY_ID="GET_USER_BY_ID";

// CAR CONSTANT
export const CREATE_CAR="CREATE_CAR";
export const GET_ALL_CAR="GET_ALL_CAR";
export const GET_ALL_CAR_BY_ID="GET_ALL_CAR_BY_ID";

// CAR SERVICES CONSTANT
export const CREATE_CAR_SERVICES="CREATE_CAR_SERVICES";
export const GET_ALL_CAR_SERVICES_LIST="GET_ALL_CAR_SERVICES_LIST";
